-- Create FAQs table
create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  "order" integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.faqs enable row level security;

-- Create policies (assuming public read, authenticated write)
create policy "Enable read access for all users" on public.faqs for select using (true);
create policy "Enable insert for authenticated users only" on public.faqs for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.faqs for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.faqs for delete using (auth.role() = 'authenticated');
