-- FIXED Permissions for FAQS table
-- Run this in Supabase Dashboard > SQL Editor

-- 1. Ensure the table exists (sanity check) and enable RLS
CREATE TABLE IF NOT EXISTS public.faqs (
    id bigint generated by default as identity primary key,
    question text not null,
    answer text not null,
    "order" integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;

-- 2. GRANT usage on Schema (Essential for permissions)
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;

-- 3. GRANT specific table permissions
-- Service Role needs EVERYTHING
GRANT ALL ON TABLE public.faqs TO service_role;
-- Anon and Authenticated need READ ONLY (Select)
GRANT SELECT ON TABLE public.faqs TO anon, authenticated;
-- Authenticated users (if any) need WRITE if you want them to edit from client-side
-- But for now let's stick to Service Role for admin edits.

-- 4. RESET Policies (Delete old ones to avoid conflicts)
DROP POLICY IF EXISTS "Public Read Access" ON public.faqs;
DROP POLICY IF EXISTS "Authenticated Write Access" ON public.faqs;
DROP POLICY IF EXISTS "Authenticated Update Access" ON public.faqs;
DROP POLICY IF EXISTS "Authenticated Delete Access" ON public.faqs;
DROP POLICY IF EXISTS "Service Role Full Access" ON public.faqs;
DROP POLICY IF EXISTS "Allow all access for all users" ON public.faqs;

-- 5. RE-CREATE Policies
-- Policy A: Everyone can read
CREATE POLICY "Public Read Access" 
ON public.faqs FOR SELECT 
USING (true);

-- Policy B: Service Role has FULL ACCESS
-- This policy uses the JWT role claim 'service_role'
CREATE POLICY "Service Role Full Access" 
ON public.faqs FOR ALL 
USING (auth.role() = 'service_role') 
WITH CHECK (auth.role() = 'service_role');

-- Optional: If you want logged-in users to edit (via client side), uncomment:
-- CREATE POLICY "Authenticated Edits" ON public.faqs FOR ALL USING (auth.role() = 'authenticated');
