import {
  Mountain,
  Wind,
  Waves,
  BedDouble,
  Bath,
  Heater,
  Dumbbell,
  Goal,
  Gamepad2,
  Clapperboard,
  ThermometerSun,
  Thermometer,
  Award,
  Wifi,
  Sparkles,
  Shirt,
  Plug,
  Coffee,
  Utensils,
  Microwave,
  GlassWater,
  WashingMachine,
  Grid3x3,
  Lock,
  Droplets,
  Flame,
  UtensilsCrossed,
  Armchair,
  Sun,
  ChefHat,
  ArrowUp,
  Baby,
  Shield,
  Dices,
  Heart,
  Trees,
  Home
} from "lucide-react";

export const iconMap: Record<string, React.ElementType> = {
  Mountain,
  Wind,
  Waves,
  BedDouble,
  Bath,
  Heater,
  Dumbbell,
  Goal,
  Gamepad2,
  Clapperboard,
  ThermometerSun,
  Thermometer,
  Award,
  Wifi,
  Sparkles,
  Shirt,
  Plug,
  Coffee,
  Utensils,
  Microwave,
  GlassWater,
  WashingMachine,
  Grid3x3,
  Lock,
  Droplets,
  Flame,
  UtensilsCrossed,
  Armchair,
  Sun,
  ChefHat,
  ArrowUp,
  Baby,
  Shield,
  Dices,
  Heart,
  Trees,
  Home
};

export const allAmenities = [
  // Premium
  {
    id: "casa_sobre_barranco",
    name: "Casa sobre Barranco",
    icon: Mountain,
    category: "Premium",
  },
  {
    id: "aire_acondicionado_full",
    name: "A/A Total",
    icon: Wind,
    category: "Premium",
  },
  {
    id: "piscina_interior_climatizada",
    name: "Piscina interior climatizada",
    icon: Waves,
    category: "Premium",
  },
  {
    id: "sommiers_king_size",
    name: "Sommiers King Size",
    icon: BedDouble,
    category: "Premium",
  },
  {
    id: "hidromasaje_4x",
    name: "Hidromasaje 4x",
    icon: Bath,
    category: "Premium",
  },
  {
    id: "sauna",
    name: "Sauna",
    icon: Heater,
    category: "Premium",
  },
  {
    id: "gimnasio_cubierto",
    name: "Gimnasio cubierto",
    icon: Dumbbell,
    category: "Premium",
  },
  {
    id: "instalacion_deportiva",
    name: "Instalación deportiva",
    icon: Goal,
    category: "Premium",
  },
  {
    id: "sala_de_juegos",
    name: "Sala de juegos",
    icon: Gamepad2,
    category: "Premium",
  },
  {
    id: "minicine_4k",
    name: "Minicine 4K",
    icon: Clapperboard,
    category: "Premium",
  },
  {
    id: "climatizador_piscina_externa",
    name: "Climatizador piscina exterior",
    icon: ThermometerSun,
    category: "Premium",
  },
  {
    id: "calefaccion_central",
    name: "Calefacción central",
    icon: Thermometer,
    category: "Premium",
  },
  {
    id: "toalleros_calefaccionados",
    name: "Toalleros calefaccionados",
    icon: Heater,
    category: "Premium",
  },
  {
    id: "calidad_constructiva",
    name: "Calidad constructiva",
    icon: Award,
    category: "Premium",
  },
  {
    id: "starlink_250",
    name: "Starlink 250",
    icon: Wifi,
    category: "Premium",
  },
  {
    id: "starlink_100",
    name: "Starlink 100",
    icon: Wifi,
    category: "Premium",
  },
  {
    id: "servicio_de_mucama",
    name: "Servicio de Mucama",
    icon: Sparkles,
    category: "Premium",
  },
  {
    id: "servicio_de_blanco_premium",
    name: "Servicio de blanco premium",
    icon: Shirt,
    category: "Premium",
  },

  // Generales
  {
    id: "pequenos_electrodomesticos",
    name: "Pequeños electrodomesticos",
    icon: Plug,
    category: "Generales",
  },
  {
    id: "cafetera_de_capsulas",
    name: "Cafetera de cápsulas",
    icon: Coffee,
    category: "Generales",
  },
  {
    id: "licuadora",
    name: "Licuadora",
    icon: Utensils,
    category: "Generales",
  },
  {
    id: "mixer",
    name: "Mixer",
    icon: Utensils,
    category: "Generales",
  },
  {
    id: "hornito_grill_electrico",
    name: "Hornito Grill eléctrico",
    icon: Microwave,
    category: "Generales",
  },
  {
    id: "juguera_electrica",
    name: "Juguera eléctrica",
    icon: GlassWater,
    category: "Generales",
  },
  {
    id: "lavarropas",
    name: "Lavarropas",
    icon: WashingMachine,
    category: "Generales",
  },
  {
    id: "secador_de_pelo",
    name: "Secador de pelo",
    icon: Wind,
    category: "Generales",
  },
  {
    id: "mosquiteros",
    name: "Mosquiteros",
    icon: Grid3x3,
    category: "Generales",
  },
  {
    id: "caja_de_seguridad",
    name: "Caja de seguridad",
    icon: Lock,
    category: "Generales",
  },
  {
    id: "lavavajillas",
    name: "Lavavajillas",
    icon: Droplets,
    category: "Generales",
  },
  {
    id: "equipo_de_planchar",
    name: "Equipo de planchar",
    icon: Shirt,
    category: "Generales",
  },
  {
    id: "hogar",
    name: "Hogar",
    icon: Flame, // Or Home
    category: "Generales",
  },
  {
    id: "wifi",
    name: "Wifi",
    icon: Wifi,
    category: "Generales",
  },

  // Exteriores
  {
    id: "piscina_privada",
    name: "Piscina privada",
    icon: Waves,
    category: "Exteriores",
  },
  {
    id: "juego_de_comedor_externo",
    name: "Juego de comedor externo",
    icon: UtensilsCrossed,
    category: "Exteriores",
  },
  {
    id: "juego_de_living_externo",
    name: "Juego de living externo",
    icon: Armchair,
    category: "Exteriores",
  },
  {
    id: "parrilla_cubierta",
    name: "Parrilla cubierta",
    icon: Flame,
    category: "Exteriores",
  },
  {
    id: "galeria",
    name: "Galeria",
    icon: Sun,
    category: "Exteriores",
  },
  {
    id: "horno_no_convencional",
    name: "Horno no convencional",
    icon: ChefHat,
    category: "Exteriores",
  },
  {
    id: "solarium_con_reposeras",
    name: "Solarium con reposeras",
    icon: Sun,
    category: "Exteriores",
  },
  {
    id: "playa_humeda",
    name: "Playa húmeda",
    icon: Droplets,
    category: "Exteriores",
  },
  {
    id: "trampolin",
    name: "Trampolín",
    icon: ArrowUp,
    category: "Exteriores",
  },
  {
    id: "tobogan_acuatico",
    name: "Tobogan acuatico",
    icon: Waves,
    category: "Exteriores",
  },
  {
    id: "juegos_para_ninos",
    name: "Juegos para niños",
    icon: Baby,
    category: "Exteriores",
  },
  {
    id: "cerco_perimetral_en_piscina",
    name: "Cerco perimetral en piscina",
    icon: Shield,
    category: "Exteriores",
  },
  {
    id: "mesas_de_juegos_externas",
    name: "Mesas de juegos externas",
    icon: Dices,
    category: "Exteriores",
  },
  {
    id: "plaza_saludable",
    name: "Plaza Saludable",
    icon: Heart,
    category: "Exteriores",
  },
  {
    id: "quincho",
    name: "Quincho",
    icon: Home,
    category: "Exteriores",
  },
  {
    id: "asador_descubierto",
    name: "Asador descubierto",
    icon: Flame,
    category: "Exteriores",
  },
  {
    id: "parque_1500_m2",
    name: "Parque +1500 m2",
    icon: Trees,
    category: "Exteriores",
  },
];
